create database jd2_airsales
    with owner postgres;

create table if not exists airport
(
    airport_id         smallint generated by default as identity (maxvalue 32767)
        constraint airports_pkey
            primary key,
    airport_name       varchar(200) not null
        constraint airports_idx_airports_name01
            unique,
    airport_short_name varchar(4)   not null
        constraint airport_airport_short_name_key
            unique,
    airpot_location    varchar(100)
        constraint airport_airpot_location_key
            unique
);

alter table airport
    owner to postgres;

create table if not exists roles
(
    roles_id    smallint generated by default as identity (maxvalue 32767)
        constraint roles_pkey
            primary key,
    role_name   varchar(20) not null
        constraint roles_idx_role_name02
            unique,
    permissions varchar(30) not null
);

alter table roles
    owner to postgres;

create index if not exists roles_idx_role_name01
    on roles (role_name);

create table if not exists airline
(
    airline_id         smallint generated by default as identity (maxvalue 32767)
        constraint "Airline_pkey"
            primary key,
    airline_name       varchar(100) not null
        constraint airline_airline_name_key
            unique
        constraint airline_idx_airline_name01
            unique
        constraint airline_idx_airline_name02
            unique,
    airline_short_name varchar(2)   not null
        constraint airline_idx_airline_short_name01
            unique
        constraint airline_idx_airline_short_name02
            unique
);

alter table airline
    owner to postgres;

create index if not exists "Airline_idx_airline_short_name01"
    on airline (airline_short_name);

create table if not exists plane
(
    plane_id        integer generated by default as identity
        constraint "Plane_pkey"
            primary key,
    aircraft_number varchar(9) not null
        constraint plane_aircraft_number_key
            unique
        constraint plane_idx_aircraft_number01
            unique,
    properties      varchar(100)
);

alter table plane
    owner to postgres;

create table if not exists seat_class
(
    seat_class_id   smallint generated by default as identity (maxvalue 32767)
        constraint seat_class_pkey
            primary key,
    seat_class_name varchar(30) not null
        constraint seat_class_idx_seat_class_name01
            unique
        constraint seat_class_seat_class_name_key
            unique
);

alter table seat_class
    owner to postgres;

create table if not exists plane_seats
(
    plane_seats_id  integer generated by default as identity
        constraint plane_seats_pkey
            primary key,
    plane           integer  not null
        constraint "FK_planeseats_plane"
            references plane,
    seat_class      smallint not null
        constraint "FK_planeseats_seatclass"
            references seat_class,
    number_of_seats smallint not null
);

alter table plane_seats
    owner to postgres;

create index if not exists plane_seats_idx_plane01
    on plane_seats (plane);

create table if not exists airline_plane
(
    plane   bigint   not null
        constraint "FK_airlineplane_plane"
            references plane,
    airline smallint not null
        constraint "FK_airlineplane_airline"
            references airline,
    constraint airline_plane_pkey
        primary key (plane, airline)
);

alter table airline_plane
    owner to postgres;

create table if not exists flight
(
    flight_id           integer generated by default as identity
        constraint flight_pkey
            primary key,
    flight_number       varchar(7) not null,
    airline             smallint   not null
        constraint "FK_flight_airline"
            references airline,
    airport_departure   smallint   not null
        constraint "FK_flightdeparture_airport"
            references airport,
    airport_destination smallint   not null
        constraint "FK_flightDestination_airport"
            references airport
);

alter table flight
    owner to postgres;

create index if not exists flight_idx_flight_number01
    on flight (flight_number);

create table if not exists flight_plane
(
    flight integer not null
        constraint "FK_flightplane_flight"
            references flight,
    plane  integer not null
        constraint "FK_flifhtplane_plane"
            references plane,
    constraint flight_plane_pkey
        primary key (flight, plane)
);

alter table flight_plane
    owner to postgres;

create table if not exists current_flight
(
    current_flight_id bigint generated by default as identity
        constraint current_flight_pkey
            primary key,
    flight            integer not null
        constraint "FK_currentflight_flight"
            references flight,
    departure_date    date    not null,
    arrival_date      date    not null,
    baseprise         money   not null
);

alter table current_flight
    owner to postgres;

create table if not exists discount
(
    discount_id    smallint generated by default as identity (maxvalue 32767)
        constraint discount_pkey
            primary key,
    discount_name  varchar(30) not null
        constraint discount_idx_discount_name01
            unique,
    discount_value smallint    not null
);

alter table discount
    owner to postgres;

create table if not exists passanger_class
(
    passanger_class_id         smallint generated by default as identity (maxvalue 32767)
        constraint passanger_class_pkey
            primary key,
    passanger_class_name       varchar(30)  not null
        constraint passanger_class_passanger_class_name_key
            unique,
    passanger_class_properties varchar(100) not null
);

alter table passanger_class
    owner to postgres;

create table if not exists passanger
(
    passanger_id    integer generated by default as identity
        constraint passanger_pkey
            primary key,
    first_name      varchar(100) not null,
    last_name       varchar(100) not null,
    passanger_class smallint     not null
        constraint "FK_passanger_passengerclass"
            references passanger_class,
    comments        varchar(100)
);

alter table passanger
    owner to postgres;

create table if not exists "user"
(
    user_id   integer generated by default as identity
        constraint users_pkey
            primary key,
    user_role smallint default 1 not null
        constraint "FK_user_roles"
            references roles,
    login     varchar(40)        not null
        constraint user_idx_login02
            unique,
    password  varchar(40)        not null,
    passanger integer
        constraint user_passanger_key
            unique
        constraint "FK_user_passenger"
            references passanger
);

alter table "user"
    owner to postgres;

create table if not exists ticket
(
    ticket_id      bigint generated by default as identity
        constraint ticket_pkey
            primary key,
    passenger      integer  not null
        constraint "FK_ticket_passnger"
            references passanger,
    current_flight bigint
        constraint "FK_ticket_currentflight"
            references current_flight,
    discount       smallint not null
        constraint "FK_ticket_diskount"
            references discount,
    finalprice     money    not null
);

alter table ticket
    owner to postgres;

create index if not exists passanger_idx_last_name01
    on passanger (last_name);

create table if not exists country
(
    country_id   smallint generated by default as identity (maxvalue 32767)
        constraint country_pkey
            primary key,
    country_name varchar(150) not null
        constraint country_idx_country_name01
            unique
);

alter table country
    owner to postgres;

create table if not exists passport
(
    passport_id      integer      not null
        constraint passport_pkey
            primary key
        constraint "FK_passport_passanger"
            references passanger,
    first_name_latin varchar(100) not null,
    last_name_latin  varchar(100) not null,
    series           varchar(12)  not null,
    expire_date      date         not null,
    citizenship      smallint     not null
        constraint "FK_passport_country"
            references country
);

alter table passport
    owner to postgres;

